apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "aws-cloudflare-api-key"
spec:
  externalSecretName: "aws-cloudflare-api-key"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: external-dns
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: cloudflare-api-key
      creationPolicy: Owner
    data:
    - secretKey: cloudflare-api-key
      remoteRef:
        key: cloudflare_api_key
