apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-email-secrets-hash-key"
spec:
  externalSecretName: "backend-email-secrets-hash-key"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-email-secrets-hash-key"
      creationPolicy: Owner
    data:
    - secretKey: "backend-email-secrets-hash-key"
      remoteRef:
        key: "backend/EmailSecrets/EmailHashKey"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-email-verification-token-hash-key"
spec:
  externalSecretName: "backend-email-verification-token-hash-key"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-email-verification-token-hash-key"
      creationPolicy: Owner
    data:
    - secretKey: "backend-email-verification-token-hash-key"
      remoteRef:
        key: "backend/EmailSecrets/EmailVerificationTokenHashKey"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-resend-key"
spec:
  externalSecretName: "backend-resend-key"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-resend-key"
      creationPolicy: Owner
    data:
    - secretKey: "backend-resend-key"
      remoteRef:
        key: "backend/ResendKey"
