apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-email-secrets-hash-key"
spec:
  externalSecretName: "backend-email-secrets-hash-key"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-email-secrets-hash-key"
      creationPolicy: Owner
    data:
    - secretKey: "backend-email-secrets-hash-key"
      remoteRef:
        key: "backend/EmailSecrets/EmailHashKey"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-email-verification-token-hash-key"
spec:
  externalSecretName: "backend-email-verification-token-hash-key"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-email-verification-token-hash-key"
      creationPolicy: Owner
    data:
    - secretKey: "backend-email-verification-token-hash-key"
      remoteRef:
        key: "backend/EmailSecrets/EmailVerificationTokenHashKey"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-resend-key"
spec:
  externalSecretName: "backend-resend-key"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-resend-key"
      creationPolicy: Owner
    data:
    - secretKey: "backend-resend-key"
      remoteRef:
        key: "backend/ResendKey"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-database-connections-main-database"
spec:
  externalSecretName: "backend-database-connections-main-database"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-database-connections-main-database"
      creationPolicy: Owner
    dataFrom:
    - extract:
        key: "backend/DatabaseConnections/MainDatabase"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-database-connections-data-protection-database"
spec:
  externalSecretName: "backend-database-connections-data-protection-database"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-database-connections-data-protection-database"
      creationPolicy: Owner
    dataFrom:
    - extract:
        key: "backend/DatabaseConnections/DataProtectionDatabase"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-openiddict-certificates-meta"
spec:
  externalSecretName: "backend-openiddict-certificates-meta"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-openiddict-certificates-meta"
      creationPolicy: Owner
    dataFrom:
    - extract:
        key: "backend/OpenIdDictCertificatesMeta"
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "backend-openiddict-certificates"
spec:
  externalSecretName: "backend-openiddict-certificates"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "backend-openiddict-certificates"
      creationPolicy: Owner
    data:
    - secretKey: "server-encryption-certificate.pfx"
      remoteRef:
        key: "backend/OpenIdDictCertificates"
        property: "server-encryption-certificate"
    - secretKey: "server-signing-certificate.pfx"
      remoteRef:
        key: "backend/OpenIdDictCertificates"
        property: "server-signing-certificate"
