apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: ingress-to-backend
spec:
  destination:
    name: backend
  sources:
    - name: ingress-gateway
      action: allow
