name: Plan and Apply

on: 
  workflow_call:
        inputs:
          workspace_name:
            description: 'Workspace name'
            required: true
            type: string
            default: 'default'
          layer:
            description: 'Layer name which have to be deployed (e.g. bootstrap, ops, app)'
            type: string
            default: bootstrap
        secrets:
          AWS_ACCOUNT_ID: 
            required: true

permissions:
  id-token: write

jobs:
  plan:
    name: Terraform plan
    uses: ./.github/workflows/actions/terraform-plan.yml
    secrets: inherit
    with:
      workspace_name: ${{ inputs.workspace_name }}
      layer: ${{ inputs.layer }}

  apply:
    name: Terraform apply
    if: ${{ needs.plan.outputs.plan_exitcode == '2' }} 
    uses: ./.github/workflows/actions/terraform-apply.yml
    secrets: inherit
    needs: [ "plan" ]
    with:
      workspace_name: ${{ inputs.workspace_name }}
      layer: ${{ inputs.layer }}