apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: "frontend-secrets"
spec:
  externalSecretName: "frontend-secrets"
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: app
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h0m0s
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: "frontend-secrets"
      creationPolicy: Owner
    data:
    - secretKey: "NUXT_OIDC_PROVIDERS_OIDC_CLIENT_SECRET"
      remoteRef:
        key: "frontend/secrets"
        property: "NUXT_OIDC_PROVIDERS_OIDC_CLIENT_SECRET"
    - secretKey: "NUXT_OIDC_TOKEN_KEY"
      remoteRef:
        key: "frontend/secrets"
        property: "NUXT_OIDC_TOKEN_KEY"
    - secretKey: "NUXT_OIDC_SESSION_SECRET"
      remoteRef:
        key: "frontend/secrets"
        property: "NUXT_OIDC_SESSION_SECRET"
    - secretKey: "NUXT_OIDC_AUTH_SESSION_SECRET"
      remoteRef:
        key: "frontend/secrets"
        property: "NUXT_OIDC_AUTH_SESSION_SECRET"
