apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awslbcontroller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    namespace: 'kube-system'
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://aws.github.io/eks-charts'
      chart: aws-load-balancer-controller
      targetRevision: 3.0.0
      helm:
        valueFiles:
          - $values/helm-values/awslbcontroller.yaml
    - repoURL: 'https://github.com/AnonymousUniverityReviews/infra.git'
      targetRevision: infra
      ref: values
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
