apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awslbcontroller-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: 'default'
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://github.com/AnonymousUniverityReviews/infra.git'
      targetRevision: infra
      path: kubernetes/awslbcontroller/crd
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
