container:
  image:
    tag: email-sending-config-c6a2c9d

podAnnotations: {
  "consul.hashicorp.com/connect-inject": "true",
  "consul.hashicorp.com/enable-metrics": "true",
  "consul.hashicorp.com/enable-metrics-merging": "true",
}