container:
  image:
    tag: dev-483de57

podAnnotations: {
  "consul.hashicorp.com/connect-inject": "true",
  "consul.hashicorp.com/enable-metrics": "true",
  "consul.hashicorp.com/enable-metrics-merging": "true",
}