name: Destroy infra
run-name: ${{ github.actor }} - terraform destroy layer-${{ inputs.layer }} workspace-${{ inputs.workspace_name }}
on: 
    workflow_call:
        inputs:
          workspace_name:
            description: 'Workspace name'
            required: true
            type: string
            default: 'default'
          layer:
            description: 'Layer name which have to be destroyed (e.g. bootstrap, ops, app)'
            type: string
            default: bootstrap
    workflow_dispatch:
      inputs:
        workspace_name:
          description: 'Workspace name'
          required: true
          type: string
          default: 'default'
        layer:
          description: 'Layer name which have to be destroyed'
          required: true
          default: 'bootstrap'
          type: choice
          options:
            - bootstrap
            - ops
            - app

permissions:
  id-token: write
  contents: read

jobs: 
    destroy:
        runs-on: ubuntu-latest
        concurrency:
          group: terraform-state
          cancel-in-progress: false
        defaults:
          run:
            working-directory: ./terraform/layers/${{ inputs.layer }}
        env:
            TF_IN_AUTOMATION: true
        steps:
            - uses: actions/checkout@v5
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v5.1.1
              with:
                role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github_actions_oidc
                role-session-name: GHA_TF_DESTROY
                aws-region: eu-central-1
            - uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init -input=false

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Select Workspace
              run: |
                terraform workspace select ${{ inputs.workspace_name }}
            - name: Terraform Destroy
              run: terraform destroy -var="name=${{ inputs.workspace_name }}" -lock=true -lock-timeout=5m -auto-approve -input=false
